const approveEmail = require('./templates/approve-email')
const approvedWithdrawalEvent = require('./templates/approved-withdrawal-event')
const completedTaskEvent = require('./templates/completed-task-event')
const confirmationEmail = require('./templates/confirmation-email')
const confirmedDepositEvent = require('./templates/confirmed-deposit-event')
const cryptoDepositReceived = require('./templates/crypto-deposit-received')
const invitationEmail = require('./templates/invitation-email')
const manualTaskCompletion = require('./templates/manual-task-completion')
const newInvitedUserEvent = require('./templates/new-invited-user-event')
const newUserEvent = require('./templates/new-user-event')
const newWithdrawalEvent = require('./templates/new-withdrawal-event')
const orderCanceled = require('./templates/order-canceled')
const orderCreated = require('./templates/order-created')
const orderFulfilled = require('./templates/order-fulfilled')
const orderPaidEvent = require('./templates/order-paid-event')
const orderPaid = require('./templates/order-paid')
const orderRefunded = require('./templates/order-refunded')
const rejectedWithdrawalEvent = require('./templates/rejected-withdrawal-event')
const resetPassword = require('./templates/reset-password')
const reviewWithdrawalEvent = require('./templates/review-withdrawal-event')
const waitApprovalAdmin = require('./templates/wait-approval-admin')

const options = { noEscape: true }
const result = waitApprovalAdmin({ locale: 'en', options })

console.log(result)
